[package]
name = "compendium"
version = "0.1.0"
authors = ["erickosamudera <ericko.samudera@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
rusqlite = "0.24.1"